workflows:
  android-workflow-dev:
    name: Android Workflow Dev
    environment: 
      android_signing:
        - keystore_reference
      flutter: 3.3.10
    scripts:
      - name: active fvm
        script: dart pub global activate fvm
      - name: fvm install
        script: fvm install
      - name: active melos 
        script: |
          flutter pub global activate melos
      - name: melos bootstrap 
        script: |
          flutter pub global run melos bs
      - name: melos run build 
        script: |
          flutter pub global run melos run app:android:release
    artifacts:
      - apps/mobile/build/app/outputs/apk/*.apk

