name: boilerplate

packages:
  - shared/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .
  
  intl:generate: 
    exec: fvm flutter pub run intl_utils:generate
    select-package:
      scope: 'mobile'

ide:
  intellij:
    enabled: false

sdkPath: .fvm/flutter_sdk
