name: boilerplate

packages:
  - shared/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .  

  intl:generate:
    name: app_intl
    description: 'generate intl utils for mobile packages'
    run: cd apps/mobile && fvm flutter pub run intl_utils:generate

  pod:install:
    name: app_intl
    description: 'pod install'
    run: cd apps/mobile/ios && pod install

  core:intl:generate:
    name: app_intl
    description: 'generate intl utils for core package'
    run: cd shared/core && fvm flutter pub run intl_utils:generate

  app:get: 
    name: app_get
    description: 'run app pub get only'
    run: cd apps/mobile && fvm flutter pub get


ide:
  intellij:
    enabled: false

sdkPath: .fvm/flutter_sdk
