name: boilerplate

packages:
  - shared/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .  

  intl:generate:
    name: app_intl
    description: 'generate intl utils for mobile packages'
    run: cd apps/mobile && fvm flutter pub run intl_utils:generate

  build:runner: 
    name: app_build_runner
    description: 'app build runner'
    run: cd apps/mobile && fvm flutter pub run build_runner build --delete-conflicting-outputs

  pod:install:
    name: pod_install_app
    description: 'pod install'
    run: cd apps/mobile/ios && pod install

  core:intl:generate:
    name: core_intl
    description: 'generate intl utils for core package'
    run: cd shared/core && fvm flutter pub run intl_utils:generate

  app:get: 
    name: app_get
    description: 'run app pub get only'
    run: cd apps/mobile && fvm flutter pub get

  image:gen:
    name: gen_image
    description: 'generate assets class'
    run: bash scripts/image_gen.sh
  

  pre:env:
    name: prepare_env
    description: 'prepare env'
    run: bash scripts/prepare_env.sh
    
      
  


  

ide:
  intellij:
    enabled: false

sdkPath: .fvm/flutter_sdk
