
include: package:flutter_lints/flutter.yaml


analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    # allow having TODOs in the code
    todo: ignore
  exclude: 
    - lib/**.g.dart
    - build/**

linter: 
  rules:
    depend_on_referenced_packages: false
    always_use_package_imports: true

