include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    # allow having TODOs in the code
    todo: ignore
    
  exclude: 
    - lib/**.g.dart
    - build/**
    - lib/generated/

linter: 
  rules:
    # style
    camel_case_types: true
    camel_case_extensions: true
    library_names: true
    file_names: true
    library_prefixes: true
    curly_braces_in_flow_control_structures: true
    avoid_field_initializers_in_const_classes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    directives_ordering: true

    #usage
    prefer_relative_imports: true
    avoid_relative_lib_imports: true

    #ignore
    no_leading_underscores_for_local_identifiers: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false