name: core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  http: ^0.13.5
  retrofit: ^3.3.1
  
  json_annotation: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  

flutter:


