name: core
description: A core package.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  http: ^0.13.5
  retrofit: ^3.3.1
  
  #Json
  json_annotation: ^4.7.0

  # Image
  extended_image: ^6.3.4
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

  #Form
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0

  # STORAGE
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^7.0.1

  #Widgets
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  loader_overlay: ^2.1.0
  animations: ^2.0.7

  # state management
  get_it: ^7.2.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.1



  #Utils
  universal_platform: ^1.0.0+1
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.5
  flutter_image_compress: ^1.1.3
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  diacritic: ^0.1.3
  intl: ^0.17.0
  intl_utils: ^2.8.1
  url_strategy: ^0.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  

flutter:

  assets: 
    - assets/icons/


flutter_intl:
  enabled: true
  class_name: SCore
  main_locale: en
  arb_dir: l10n
  output_dir: lib/generated
