# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  build_time = Time.now.strftime('%Y%m%d')
  # //version_name = get_info_plist_value(path: "./Runner/Info.plist", key: "CFBundleShortVersionString")

  lane :release do 
    gym(
      scheme: "Runner", 
      workspace: "Runner.xcworkspace", 
      output_directory: "./build", 
      output_name: "Runner.ipa",
      clean: false, 
      configuration: "Release",
      include_bitcode: false,
      xcargs: "-UseModernBuildSystem=YES",
      export_team_id: "5NM2W52AY4",
      export_method: "ad-hoc",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end

  lane :prodrelease do 
    gym(
      scheme: "Runner", 
      workspace: "Runner.xcworkspace", 
      output_directory: "./build", 
      output_name: "Runner.ipa",
      clean: false, 
      configuration: "Release",
      include_bitcode: false,
      xcargs: "-UseModernBuildSystem=YES",
      export_team_id: "PGWP4VJHLX",
      export_method: "ad-hoc",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end

  lane :uploadstore do 
    file_name = "app-#{build_time}"
    gym(
      scheme: "Runner", 
      workspace: "Runner.xcworkspace", 
      output_directory: "./build",
      output_name: "#{file_name}-appstore.ipa",
      clean: true, 
      configuration: "Release",
      include_bitcode: false,
      xcargs: "-UseModernBuildSystem=YES",
      export_team_id: "PGWP4VJHLX",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end
end

